export { default as AdminAdd } from "./AdminAdd"
export { default as AdminDetail } from "./AdminDetail"
export { default as AdminHome } from "./AdminHome"
export { default as AdminList } from "./AdminList"
export { default as UserDetail } from "./UserDetail"
export { default as UserHome } from "./UserHome"